volumes:
  postgres-data:

networks:
  developnet:
    driver: bridge
    internal: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PATH=/workspaces/pua/bin:/workspaces/pua/scripts:/workspaces/pua/node_modules/.bin:${PATH}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 8081:8081
    volumes:
      - ..:/workspaces/pua:consistent
    command: sleep infinity
    working_dir: /workspaces/pua
    networks:
      - developnet
      - default

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - developnet

  redis:
    image: redis:latest
